package org.campagnelab.antlr.tomps.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.impl.query.QueryProviderBase;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.campagnelab.antlr.tomps.behavior.AlternativeMapper__BehaviorDescriptor;
import org.campagnelab.antlr.tomps.behavior.ConceptMapper__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import org.jetbrains.mps.openapi.model.SNode;
import org.campagnelab.antlr.tomps.behavior.Source__BehaviorDescriptor;
import org.campagnelab.antlr.tomps.behavior.ConvertToMPS__BehaviorDescriptor;
import jetbrains.mps.generator.template.IfMacroContext;
import org.campagnelab.ANTLR.behavior.ParserRuleBlock__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import java.util.Objects;
import org.campagnelab.antlr.tomps.behavior.Destination__BehaviorDescriptor;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import java.util.Map;
import jetbrains.mps.generator.impl.query.SourceNodeQuery;
import java.util.HashMap;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.impl.query.QueryKey;
import jetbrains.mps.generator.impl.query.QueryKeyImpl;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.generator.impl.GenerationFailureException;
import jetbrains.mps.generator.impl.query.SourceNodesQuery;
import java.util.Collection;
import jetbrains.mps.util.IterableUtil;
import jetbrains.mps.generator.impl.query.PropertyValueQuery;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.generator.impl.query.IfMacroCondition;
import jetbrains.mps.generator.impl.query.ReferenceTargetQuery;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.smodel.SModelUtil_new;

@Generated
public class QueriesGenerated extends QueryProviderBase {
  public QueriesGenerated() {
    super(1);
  }
  public static Object propertyMacro_GetPropertyValue_4522383332297425071(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x3ec2bbae1bba463bL, 0x3ec2bbae1bba463cL, "trim"));
  }
  public static Object propertyMacro_GetPropertyValue_1229604057029480871(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea6061b82L, 0x6a1bb02ea6061be9L, "grammar")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "_ToMpsVisitor";
  }
  public static Object propertyMacro_GetPropertyValue_1229604057030820087(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x69d936b00a0eba02L, 0x69d936b00a0eba05L, "rule")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_558881339902552449(final PropertyMacroContext _context) {
    return (String) AlternativeMapper__BehaviorDescriptor.subConceptPrefix_idv1yTSorHAC.invoke(_context.getNode());
  }
  public static Object propertyMacro_GetPropertyValue_558881339892992162(final PropertyMacroContext _context) {
    return "visit" + ConceptMapper__BehaviorDescriptor.upperCaseFirstChar_id4gYz4fZSN_K.invoke(_context.getNode(), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x69d936b00a0eba02L, 0x69d936b00a0eba05L, "rule")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"))) + "";
  }
  public static Object propertyMacro_GetPropertyValue_1229604057030812155(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea606232bL, 0x6a1bb02ea6062391L, "alternative")), MetaAdapterFactory.getProperty(0xd6782141eafa4cf7L, 0xa85d1229abdb1152L, 0x631eebe3113b458fL, 0x6d831d6acef0ba05L, "label"));
  }
  public static Object propertyMacro_GetPropertyValue_8933086517772282959(final PropertyMacroContext _context) {

    String label = (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea606232bL, 0x6a1bb02ea6062391L, "alternative")), MetaAdapterFactory.getProperty(0xd6782141eafa4cf7L, 0xa85d1229abdb1152L, 0x631eebe3113b458fL, 0x6d831d6acef0ba05L, "label")) == null ? "noLabel" : AlternativeMapper__BehaviorDescriptor.upperCaseFirstChar_idv1yTSoiOYi.invoke(_context.getNode(), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea606232bL, 0x6a1bb02ea6062391L, "alternative")), MetaAdapterFactory.getProperty(0xd6782141eafa4cf7L, 0xa85d1229abdb1152L, 0x631eebe3113b458fL, 0x6d831d6acef0ba05L, "label"))));
    return "visit" + label + "";
  }
  public static Object propertyMacro_GetPropertyValue_489068675543580076(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x195a5f84d619bfbdL, 0x195a5f84d619bfbeL, "name")) + ":" + Integer.toString(SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x195a5f84d619bfbdL, 0x6c9855e84f32c33L, "arity")));
  }
  public static Object propertyMacro_GetPropertyValue_558881339893120806(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea6061b82L, 0x6a1bb02ea6061be9L, "grammar")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")) + "_ToMpsVisitor";
  }
  public static Object propertyMacro_GetPropertyValue_489068675551942932(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination")), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6c9855e848a0c58L, "org.campagnelab.antlr.tomps.structure.ToOperator")), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6c9855e848a0c58L, 0x6c9855e84f34171L, "arity"));
  }
  public static Object referenceMacro_GetReferent_558881339892955174(final ReferenceMacroContext _context) {
    return String.format("%s.%sContext", SPropertyOperations.getString(ConceptMapper__BehaviorDescriptor.converter_idv1yTSnUAUT.invoke(_context.getNode()), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea6061b82L, 0x2884e9c786d8d369L, "parserCanonicalClassName")), SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x69d936b00a0eba02L, 0x69d936b00a0eba03L, "concept")));
  }
  public static Object referenceMacro_GetReferent_558881339892896039(final ReferenceMacroContext _context) {
    return (SNode) ConceptMapper__BehaviorDescriptor.visitorReturnConcept_idv1yTSnUBj7.invoke(_context.getNode());
  }
  public static Object referenceMacro_GetReferent_558881339893019882(final ReferenceMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x69d936b00a0eba02L, 0x69d936b00a0eba03L, "concept"));
  }
  public static Object referenceMacro_GetReferent_558881339893021123(final ReferenceMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x69d936b00a0eba02L, 0x69d936b00a0eba03L, "concept"));
  }
  public static Object referenceMacro_GetReferent_558881339902213637(final ReferenceMacroContext _context) {
    return (SNode) AlternativeMapper__BehaviorDescriptor.visitorReturnConcept_idv1yTSnUhdL.invoke(_context.getNode());
  }
  public static Object referenceMacro_GetReferent_6247096756522584080(final ReferenceMacroContext _context) {
    return "subConceptPrefix";
  }
  public static Object referenceMacro_GetReferent_6247096756522340050(final ReferenceMacroContext _context) {
    return "subConceptPrefix";
  }
  public static Object referenceMacro_GetReferent_8933086517772282807(final ReferenceMacroContext _context) {
    return String.format("%s.%sContext", SPropertyOperations.getString(AlternativeMapper__BehaviorDescriptor.converter_idv1yTSnUA_G.invoke(_context.getNode()), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea6061b82L, 0x2884e9c786d8d369L, "parserCanonicalClassName")), AlternativeMapper__BehaviorDescriptor.upperCaseFirstChar_idv1yTSoiOYi.invoke(_context.getNode(), SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea606232bL, 0x6a1bb02ea6062391L, "alternative")), MetaAdapterFactory.getProperty(0xd6782141eafa4cf7L, 0xa85d1229abdb1152L, 0x631eebe3113b458fL, 0x6d831d6acef0ba05L, "label"))));
  }
  public static Object referenceMacro_GetReferent_8933086517772282823(final ReferenceMacroContext _context) {
    return (SNode) AlternativeMapper__BehaviorDescriptor.visitorReturnConcept_idv1yTSnUhdL.invoke(_context.getNode());
  }
  public static Object referenceMacro_GetReferent_8933086517774776050(final ReferenceMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea606232bL, 0x7c18b9e17e92154L, "returns"));
  }
  public static Object referenceMacro_GetReferent_8933086517774776060(final ReferenceMacroContext _context) {
    return (SNode) AlternativeMapper__BehaviorDescriptor.visitorReturnConcept_idv1yTSnUhdL.invoke(_context.getNode());
  }
  public static Object referenceMacro_GetReferent_489068675543580924(final ReferenceMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x195a5f84d619bfbdL, 0x195a5f84d62a2bcaL, "concept"));
  }
  public static Object referenceMacro_GetReferent_1096804516885722969(final ReferenceMacroContext _context) {
    String parserName = SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea6061b82L, 0x2884e9c786d8d369L, "parserCanonicalClassName"));
    if (parserName.endsWith("Parser")) {
      parserName = parserName.substring(0, parserName.length() - "Parser".length());
    }
    return parserName + "BaseVisitor";
  }
  public static Object referenceMacro_GetReferent_4798834304115678174(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x3875e55a78eeb7feL, 0x3875e55a78eebf59L, "rule")), MetaAdapterFactory.getReferenceLink(0xd6782141eafa4cf7L, 0xa85d1229abdb1152L, 0x631eebe31132d966L, 0x631eebe31132d967L, "rule")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_4798834304115678633(final ReferenceMacroContext _context) {
    if (SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x3875e55a78eeb7ddL, 0x32ac4b93a6b7ec8L, "cardinality"), "0..1").equals("0..n") || SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x3875e55a78eeb7ddL, 0x32ac4b93a6b7ec8L, "cardinality"), "0..1").equals("1..n")) {
      return "visitList";
    } else {
      return "visit";
    }
  }
  public static Object referenceMacro_GetReferent_4798834304115679379(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x3875e55a78eeb7feL, 0x3875e55a78eebf59L, "rule")), MetaAdapterFactory.getReferenceLink(0xd6782141eafa4cf7L, 0xa85d1229abdb1152L, 0x631eebe31132d966L, 0x631eebe31132d967L, "rule")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_6247096756520515351(final ReferenceMacroContext _context) {
    return (String) Source__BehaviorDescriptor.name_id3xPTlDSWS6G.invoke(_context.getNode());
  }
  public static Object referenceMacro_GetReferent_6897009001583523917(final ReferenceMacroContext _context) {
    if (SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x3875e55a78eeb7ddL, 0x32ac4b93a6b7ec8L, "cardinality"), "0..1").equals("0..n") || SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x3875e55a78eeb7ddL, 0x32ac4b93a6b7ec8L, "cardinality"), "0..1").equals("1..n")) {
      return "visitList";
    } else {
      return "visit";
    }
  }
  public static Object referenceMacro_GetReferent_3737166271523378551(final ReferenceMacroContext _context) {
    return (String) Source__BehaviorDescriptor.name_id3xPTlDSWS6G.invoke(_context.getNode());
  }
  public static Object referenceMacro_GetReferent_4798834304119525000(final ReferenceMacroContext _context) {
    return (String) Source__BehaviorDescriptor.name_id3xPTlDSWS6G.invoke(_context.getNode());
  }
  public static Object referenceMacro_GetReferent_4798834304119566853(final ReferenceMacroContext _context) {
    return "visitList";
  }
  public static Object referenceMacro_GetReferent_2860118060025025004(final ReferenceMacroContext _context) {
    return "result";
  }
  public static Object referenceMacro_GetReferent_2860118060024669098(final ReferenceMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x27b12e38d7577b90L, 0x27b12e38d7577b91L, "to"));
  }
  public static Object referenceMacro_GetReferent_2860118060025897726(final ReferenceMacroContext _context) {
    return "result";
  }
  public static Object referenceMacro_GetReferent_2860118060025897495(final ReferenceMacroContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x4aaf5f3861bb9099L, 0x4aaf5f3861bb96d2L, "to"));
  }
  public static Object referenceMacro_GetReferent_1229604057031378832(final ReferenceMacroContext _context) {
    return "result";
  }
  public static Object referenceMacro_GetReferent_1229604057031381977(final ReferenceMacroContext _context) {
    return SLinkOperations.getTarget(SNodeOperations.as(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination")), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x4aaf5f3861bb9099L, "org.campagnelab.antlr.tomps.structure.ChildDestination")), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x4aaf5f3861bb9099L, 0x4aaf5f3861bb96d2L, "to"));
  }
  public static Object referenceMacro_GetReferent_6247096756518748057(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6912564f422833dbL, 0x6912564f422833dcL, "rule")), MetaAdapterFactory.getReferenceLink(0xd6782141eafa4cf7L, 0xa85d1229abdb1152L, 0x175f2668a890ef9eL, 0x175f2668a890ef9fL, "rule")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_6247096756518753323(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6912564f422833dbL, 0x6912564f422833dcL, "rule")), MetaAdapterFactory.getReferenceLink(0xd6782141eafa4cf7L, 0xa85d1229abdb1152L, 0x175f2668a890ef9eL, 0x175f2668a890ef9fL, "rule")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_4522383332296526103(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6912564f422833dbL, 0x6912564f422833dcL, "rule")), MetaAdapterFactory.getReferenceLink(0xd6782141eafa4cf7L, 0xa85d1229abdb1152L, 0x175f2668a890ef9eL, 0x175f2668a890ef9fL, "rule")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object referenceMacro_GetReferent_4522383332294679145(final ReferenceMacroContext _context) {
    return (String) ConvertToMPS__BehaviorDescriptor.getGeneratedClassName_id14grA09hT8$.invoke(SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea6061b82L, "org.campagnelab.antlr.tomps.structure.ConvertToMPS"), false, false));
  }
  public static Object referenceMacro_GetReferent_489068675549501045(final ReferenceMacroContext _context) {
    return (String) ConvertToMPS__BehaviorDescriptor.getGeneratedClassName_id14grA09hT8$.invoke(SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea6061b82L, "org.campagnelab.antlr.tomps.structure.ConvertToMPS"), false, false));
  }
  public static Object referenceMacro_GetReferent_489068675549506112(final ReferenceMacroContext _context) {
    return "mapOperator";
  }
  public static Object referenceMacro_GetReferent_1229604057017649471(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x11106e6008e38ee7L, 0x11106e60094fde78L, "generatedClassName"));
  }
  public static boolean ifMacro_Condition_558881339902083120(final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea606232bL, 0x7c18b9e17e92154L, "returns")) != null) && AlternativeMapper__BehaviorDescriptor.subConceptPrefix_idv1yTSorHAC.invoke(_context.getNode()) != null;
  }
  public static boolean ifMacro_Condition_3737166271522546415(final IfMacroContext _context) {
    return (boolean) ParserRuleBlock__BehaviorDescriptor.needsVisit_id3ft5eLKF8lT.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x4aaf5f3861adfe77L, 0x4aaf5f3861ae0179L, "labeled")), MetaAdapterFactory.getContainmentLink(0xd6782141eafa4cf7L, 0xa85d1229abdb1152L, 0x7c18b9e17b73a85L, 0x7c18b9e17b7c72fL, "element")));
  }
  public static boolean ifMacro_Condition_4798834304119501164(final IfMacroContext _context) {
    if (SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x3875e55a78eeb7ddL, 0x32ac4b93a6b7ec8L, "cardinality"), "0..1").equals("0..n") || SPropertyOperations.getString_def(_context.getNode(), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x3875e55a78eeb7ddL, 0x32ac4b93a6b7ec8L, "cardinality"), "0..1").equals("1..n")) {
      return false;
    } else {
      return true;
    }
  }
  public static boolean ifMacro_Condition_1229604057031363912(final IfMacroContext _context) {
    if (SEnumOperations.getMemberValue(SEnumOperations.getMember(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, "jetbrains.mps.lang.structure", 0xfc6f3944c2L, "Cardinality", 0xfc6f3944c4L, "1")).equals(SPropertyOperations.getString_def(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x4aaf5f3861bb9099L, 0x4aaf5f3861bb96d2L, "to")), MetaAdapterFactory.getProperty(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0xf979bd086aL, 0xf98054bb04L, "sourceCardinality"), "0..1"))) {
      return true;
    }
    if (SEnumOperations.getMemberValue(SEnumOperations.getMember(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, "jetbrains.mps.lang.structure", 0xfc6f3944c2L, "Cardinality", 0xfc6f3944c3L, "0..1")).equals(SPropertyOperations.getString_def(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x4aaf5f3861bb9099L, 0x4aaf5f3861bb96d2L, "to")), MetaAdapterFactory.getProperty(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0xf979bd086aL, 0xf98054bb04L, "sourceCardinality"), "0..1"))) {
      return true;
    }
    return false;
  }
  public static boolean ifMacro_Condition_228211030964493749(final IfMacroContext _context) {
    if (SEnumOperations.getMemberValue(SEnumOperations.getMember(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, "jetbrains.mps.lang.structure", 0xfc6f3944c2L, "Cardinality", 0xfc6f3944c4L, "1")).equals(SPropertyOperations.getString_def(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x3875e55a78ffcbddL, "source")), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x3875e55a78eeb7ddL, 0x32ac4b93a6b7ec8L, "cardinality"), "0..1"))) {
      return true;
    }
    if (SEnumOperations.getMemberValue(SEnumOperations.getMember(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, "jetbrains.mps.lang.structure", 0xfc6f3944c2L, "Cardinality", 0xfc6f3944c3L, "0..1")).equals(SPropertyOperations.getString_def(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x3875e55a78ffcbddL, "source")), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x3875e55a78eeb7ddL, 0x32ac4b93a6b7ec8L, "cardinality"), "0..1"))) {
      return true;
    }
    return false;
  }
  public static boolean ifMacro_Condition_6247096756518748787(final IfMacroContext _context) {
    SNode mapper = SNodeOperations.getNodeAncestor(_context.getNode(), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, "org.campagnelab.antlr.tomps.structure.Mapper"), false, false);
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(mapper, MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination")), MetaAdapterFactory.getInterfaceConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x11106e6008bd1727L, "org.campagnelab.antlr.tomps.structure.IToConverter")) || Objects.equals(SNodeOperations.getConcept(Destination__BehaviorDescriptor.type_id5qM9mr9Mqo7.invoke(SLinkOperations.getTarget(mapper, MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination")))), SNodeOperations.getConcept(_quotation_createNode_x583g4_a0a0a1a05())) || SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6912564f422833dbL, 0x11d5dff406a4c13dL, "forceGetText"));
  }
  public static boolean ifMacro_Condition_4522383332294651567(final IfMacroContext _context) {
    return !(SPropertyOperations.getBoolean(_context.getNode(), MetaAdapterFactory.getProperty(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6912564f422833dbL, 0x3ec2bbae1b81ad54L, "hasTrim")));
  }
  public static boolean ifMacro_Condition_1229604057013838704(final IfMacroContext _context) {
    return !((SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination")), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x443e8c43ffcc4608L, "org.campagnelab.antlr.tomps.structure.ToBooleanDestination")) || SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination")), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x443e8c43ffc0edbfL, "org.campagnelab.antlr.tomps.structure.ToIntDestination")) || SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination")), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x443e8c43ffcf6763L, "org.campagnelab.antlr.tomps.structure.ToFloatDestination")) || SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination")), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6c9855e848a0c58L, "org.campagnelab.antlr.tomps.structure.ToOperator"))));
  }
  public static boolean ifMacro_Condition_1229604057013034904(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination")), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x443e8c43ffcf6763L, "org.campagnelab.antlr.tomps.structure.ToFloatDestination"));
  }
  public static boolean ifMacro_Condition_1229604057013041225(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination")), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x443e8c43ffc0edbfL, "org.campagnelab.antlr.tomps.structure.ToIntDestination"));
  }
  public static boolean ifMacro_Condition_1229604057013048237(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination")), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x443e8c43ffcc4608L, "org.campagnelab.antlr.tomps.structure.ToBooleanDestination"));
  }
  public static boolean ifMacro_Condition_489068675543492127(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination")), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6c9855e848a0c58L, "org.campagnelab.antlr.tomps.structure.ToOperator"));
  }
  public static SNode sourceNodeQuery_1229604057031408230(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x3875e55a78ffcbddL, "source"));
  }
  public static SNode sourceNodeQuery_1229604057013838685(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination"));
  }
  public static SNode sourceNodeQuery_1229604057013838696(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x3875e55a78ffcbddL, "source"));
  }
  public static SNode sourceNodeQuery_1229604057013079256(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination")), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x443e8c43ffcf6763L, "org.campagnelab.antlr.tomps.structure.ToFloatDestination")), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x443e8c43ffcf6763L, 0x443e8c43ffcf6764L, "toConvert"));
  }
  public static SNode sourceNodeQuery_1229604057013083318(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x3875e55a78ffcbddL, "source"));
  }
  public static SNode sourceNodeQuery_5554617735686772708(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x3875e55a78ffcbddL, "source"));
  }
  public static SNode sourceNodeQuery_1229604057013784761(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination")), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x443e8c43ffc0edbfL, "org.campagnelab.antlr.tomps.structure.ToIntDestination")), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x443e8c43ffc0edbfL, 0x443e8c43ffc0edc0L, "toConvert"));
  }
  public static SNode sourceNodeQuery_1229604057013071466(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination")), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x443e8c43ffcc4608L, "org.campagnelab.antlr.tomps.structure.ToBooleanDestination")), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x443e8c43ffcc4608L, 0x443e8c43ffcc4609L, "toConvert"));
  }
  public static SNode sourceNodeQuery_1229604057013069700(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x3875e55a78ffcbddL, "source"));
  }
  public static SNode sourceNodeQuery_489068675546020966(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x4aaf5f3861bb9078L, "destination")), MetaAdapterFactory.getConcept(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6c9855e848a0c58L, "org.campagnelab.antlr.tomps.structure.ToOperator")), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6c9855e848a0c58L, 0x6c9855e848a14cfL, "toConvert"));
  }
  public static SNode sourceNodeQuery_489068675549542707(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x7c18b9e1882f81cL, 0x3875e55a78ffcbddL, "source"));
  }
  public static Iterable<SNode> sourceNodesQuery_558881339902026674(final SourceSubstituteMacroNodesContext _context) {
    return (Iterable<SNode>) ConceptMapper__BehaviorDescriptor.altMappers_idv1yTSot8er.invoke(_context.getNode());
  }
  public static Iterable<SNode> sourceNodesQuery_2919715501614612396(final SourceSubstituteMacroNodesContext _context) {
    return (Iterable<SNode>) ConceptMapper__BehaviorDescriptor.altMappers_idv1yTSot8er.invoke(_context.getNode());
  }
  public static Iterable<SNode> sourceNodesQuery_558881339892892222(final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea6061b82L, 0x69d936b00a0eba08L, "conceptMapper"))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SLinkOperations.getTarget(it, MetaAdapterFactory.getReferenceLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x69d936b00a0eba02L, 0x69d936b00a0eba03L, "concept")) != null && !((boolean) ConceptMapper__BehaviorDescriptor.hasLabels_id7JSGHIZFCiI.invoke(it));
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_8933086517772282940(final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea6061b82L, 0x6a1bb02ea6062393L, "altMappers"))).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return (boolean) AlternativeMapper__BehaviorDescriptor.hasLabels_id59EVW_fnDMp.invoke(it);
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_489068675543579382(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea6061b82L, 0x195a5f84d619bf2eL, "operators"));
  }
  public static Iterable<SNode> sourceNodesQuery_2919715501614119319(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6a1bb02ea606232bL, 0x7c18b9e1882f807L, "map"));
  }
  public static Iterable<SNode> sourceNodesQuery_4522383332297417158(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x932d719ce93144d5L, 0x990ce115f79b5942L, 0x6912564f422833dbL, 0x3ec2bbae1bba463eL, "trimSets"));
  }
  private final Map<String, SourceNodeQuery> snqMethods = new HashMap<String, SourceNodeQuery>();
  {
    int i = 0;
    snqMethods.put("1229604057031408230", new QueriesGenerated.SNQ(i++));
    snqMethods.put("1229604057013838685", new QueriesGenerated.SNQ(i++));
    snqMethods.put("1229604057013838696", new QueriesGenerated.SNQ(i++));
    snqMethods.put("1229604057013079256", new QueriesGenerated.SNQ(i++));
    snqMethods.put("1229604057013083318", new QueriesGenerated.SNQ(i++));
    snqMethods.put("5554617735686772708", new QueriesGenerated.SNQ(i++));
    snqMethods.put("1229604057013784761", new QueriesGenerated.SNQ(i++));
    snqMethods.put("1229604057013071466", new QueriesGenerated.SNQ(i++));
    snqMethods.put("1229604057013069700", new QueriesGenerated.SNQ(i++));
    snqMethods.put("489068675546020966", new QueriesGenerated.SNQ(i++));
    snqMethods.put("489068675549542707", new QueriesGenerated.SNQ(i++));
  }
  @NotNull
  @Override
  public SourceNodeQuery getSourceNodeQuery(@NotNull QueryKey identity) {
    final String id = ((QueryKeyImpl) identity).getQueryNodeId().toString();
    if (!(snqMethods.containsKey(id))) {
      return super.getSourceNodeQuery(identity);
    }
    return snqMethods.get(id);
  }
  private static class SNQ implements SourceNodeQuery {
    private final int methodKey;
    public SNQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @Nullable
    public SNode evaluate(@NotNull SourceSubstituteMacroNodeContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.sourceNodeQuery_1229604057031408230(ctx);
        case 1:
          return QueriesGenerated.sourceNodeQuery_1229604057013838685(ctx);
        case 2:
          return QueriesGenerated.sourceNodeQuery_1229604057013838696(ctx);
        case 3:
          return QueriesGenerated.sourceNodeQuery_1229604057013079256(ctx);
        case 4:
          return QueriesGenerated.sourceNodeQuery_1229604057013083318(ctx);
        case 5:
          return QueriesGenerated.sourceNodeQuery_5554617735686772708(ctx);
        case 6:
          return QueriesGenerated.sourceNodeQuery_1229604057013784761(ctx);
        case 7:
          return QueriesGenerated.sourceNodeQuery_1229604057013071466(ctx);
        case 8:
          return QueriesGenerated.sourceNodeQuery_1229604057013069700(ctx);
        case 9:
          return QueriesGenerated.sourceNodeQuery_489068675546020966(ctx);
        case 10:
          return QueriesGenerated.sourceNodeQuery_489068675549542707(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, SourceNodesQuery> snsqMethods = new HashMap<String, SourceNodesQuery>();
  {
    int i = 0;
    snsqMethods.put("558881339902026674", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("2919715501614612396", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("558881339892892222", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("8933086517772282940", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("489068675543579382", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("2919715501614119319", new QueriesGenerated.SNsQ(i++));
    snsqMethods.put("4522383332297417158", new QueriesGenerated.SNsQ(i++));
  }
  @NotNull
  @Override
  public SourceNodesQuery getSourceNodesQuery(@NotNull QueryKey identity) {
    final String id = ((QueryKeyImpl) identity).getQueryNodeId().toString();
    if (!(snsqMethods.containsKey(id))) {
      return super.getSourceNodesQuery(identity);
    }
    return snsqMethods.get(id);
  }
  private static class SNsQ implements SourceNodesQuery {
    private final int methodKey;
    public SNsQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @NotNull
    public Collection<SNode> evaluate(@NotNull SourceSubstituteMacroNodesContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_558881339902026674(ctx));
        case 1:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_2919715501614612396(ctx));
        case 2:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_558881339892892222(ctx));
        case 3:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_8933086517772282940(ctx));
        case 4:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_489068675543579382(ctx));
        case 5:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_2919715501614119319(ctx));
        case 6:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4522383332297417158(ctx));
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, PropertyValueQuery> pvqMethods = new HashMap<String, PropertyValueQuery>();
  {
    int i = 0;
    pvqMethods.put("4522383332297425068", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "trimChars"));
    pvqMethods.put("1229604057029480870", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), null));
    pvqMethods.put("1229604057030820086", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "rule.name"));
    pvqMethods.put("558881339902552448", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "function"));
    pvqMethods.put("558881339892992161", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "visitRuleContext"));
    pvqMethods.put("1229604057030812154", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "methodName"));
    pvqMethods.put("8933086517772282958", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "visitLabeledContext"));
    pvqMethods.put("489068675543580073", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf93d565d10L, 0xf93d565d11L, "value"), "=="));
    pvqMethods.put("558881339893120805", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "reduce_ConvertToMPS"));
    pvqMethods.put("489068675551942931", new QueriesGenerated.PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc59b314L, 0xf8cc59b315L, "value"), "2"));
  }
  @NotNull
  @Override
  public PropertyValueQuery getPropertyValueQuery(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(pvqMethods.containsKey(id))) {
      return super.getPropertyValueQuery(identity);
    }
    return pvqMethods.get(id);
  }
  private static class PVQ extends PropertyValueQuery.Base {
    private final int methodKey;
    /*package*/ PVQ(int methodKey, SProperty property, String templateValue) {
      super(property, templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull PropertyMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.propertyMacro_GetPropertyValue_4522383332297425071(ctx);
        case 1:
          return QueriesGenerated.propertyMacro_GetPropertyValue_1229604057029480871(ctx);
        case 2:
          return QueriesGenerated.propertyMacro_GetPropertyValue_1229604057030820087(ctx);
        case 3:
          return QueriesGenerated.propertyMacro_GetPropertyValue_558881339902552449(ctx);
        case 4:
          return QueriesGenerated.propertyMacro_GetPropertyValue_558881339892992162(ctx);
        case 5:
          return QueriesGenerated.propertyMacro_GetPropertyValue_1229604057030812155(ctx);
        case 6:
          return QueriesGenerated.propertyMacro_GetPropertyValue_8933086517772282959(ctx);
        case 7:
          return QueriesGenerated.propertyMacro_GetPropertyValue_489068675543580076(ctx);
        case 8:
          return QueriesGenerated.propertyMacro_GetPropertyValue_558881339893120806(ctx);
        case 9:
          return QueriesGenerated.propertyMacro_GetPropertyValue_489068675551942932(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, IfMacroCondition> imcMethods = new HashMap<String, IfMacroCondition>();
  {
    int i = 0;
    imcMethods.put("558881339902083118", new QueriesGenerated.IfMC(i++));
    imcMethods.put("3737166271522546413", new QueriesGenerated.IfMC(i++));
    imcMethods.put("4798834304119501162", new QueriesGenerated.IfMC(i++));
    imcMethods.put("1229604057031363910", new QueriesGenerated.IfMC(i++));
    imcMethods.put("228211030964493747", new QueriesGenerated.IfMC(i++));
    imcMethods.put("6247096756518748785", new QueriesGenerated.IfMC(i++));
    imcMethods.put("4522383332294651565", new QueriesGenerated.IfMC(i++));
    imcMethods.put("1229604057013838703", new QueriesGenerated.IfMC(i++));
    imcMethods.put("1229604057013034902", new QueriesGenerated.IfMC(i++));
    imcMethods.put("1229604057013041223", new QueriesGenerated.IfMC(i++));
    imcMethods.put("1229604057013048235", new QueriesGenerated.IfMC(i++));
    imcMethods.put("489068675543492126", new QueriesGenerated.IfMC(i++));
  }
  @NotNull
  @Override
  public IfMacroCondition getIfMacroCondition(@NotNull QueryKey identity) {
    final String id = identity.getTemplateNode().getNodeId().toString();
    if (!(imcMethods.containsKey(id))) {
      return super.getIfMacroCondition(identity);
    }
    return imcMethods.get(id);
  }
  private static class IfMC implements IfMacroCondition {
    private final int methodKey;
    public IfMC(int methodKey) {
      this.methodKey = methodKey;
    }
    @Override
    public boolean check(@NotNull IfMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.ifMacro_Condition_558881339902083120(ctx);
        case 1:
          return QueriesGenerated.ifMacro_Condition_3737166271522546415(ctx);
        case 2:
          return QueriesGenerated.ifMacro_Condition_4798834304119501164(ctx);
        case 3:
          return QueriesGenerated.ifMacro_Condition_1229604057031363912(ctx);
        case 4:
          return QueriesGenerated.ifMacro_Condition_228211030964493749(ctx);
        case 5:
          return QueriesGenerated.ifMacro_Condition_6247096756518748787(ctx);
        case 6:
          return QueriesGenerated.ifMacro_Condition_4522383332294651567(ctx);
        case 7:
          return QueriesGenerated.ifMacro_Condition_1229604057013838704(ctx);
        case 8:
          return QueriesGenerated.ifMacro_Condition_1229604057013034904(ctx);
        case 9:
          return QueriesGenerated.ifMacro_Condition_1229604057013041225(ctx);
        case 10:
          return QueriesGenerated.ifMacro_Condition_1229604057013048237(ctx);
        case 11:
          return QueriesGenerated.ifMacro_Condition_489068675543492127(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no condition method for if macro %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, ReferenceTargetQuery> rtqMethods = new HashMap<String, ReferenceTargetQuery>();
  {
    rtqMethods.put("558881339892955173", new QueriesGenerated.RTQ(0, "ActionContext"));
    rtqMethods.put("558881339892896038", new QueriesGenerated.RTQ(1, "ExampleConcept"));
    rtqMethods.put("558881339893019879", new QueriesGenerated.RTQ(2, "ExampleConcept"));
    rtqMethods.put("558881339893021122", new QueriesGenerated.RTQ(3, "ExampleConcept"));
    rtqMethods.put("558881339902213636", new QueriesGenerated.RTQ(4, "ExampleConcept"));
    rtqMethods.put("6247096756522584079", new QueriesGenerated.RTQ(5, "children"));
    rtqMethods.put("6247096756522340049", new QueriesGenerated.RTQ(6, "children"));
    rtqMethods.put("8933086517772282806", new QueriesGenerated.RTQ(7, "ActionContext"));
    rtqMethods.put("8933086517772282822", new QueriesGenerated.RTQ(8, "ExampleConcept"));
    rtqMethods.put("8933086517774776049", new QueriesGenerated.RTQ(9, "ExampleConcept"));
    rtqMethods.put("8933086517774776059", new QueriesGenerated.RTQ(10, "ExampleConcept"));
    rtqMethods.put("489068675543580921", new QueriesGenerated.RTQ(11, "ExampleConcept"));
    rtqMethods.put("1096804516885722968", new QueriesGenerated.RTQ(12, "AbstractParseTreeVisitor"));
    rtqMethods.put("4798834304115678173", new QueriesGenerated.RTQ(13, "id"));
    rtqMethods.put("4798834304115678632", new QueriesGenerated.RTQ(14, "visitRule"));
    rtqMethods.put("4798834304115679378", new QueriesGenerated.RTQ(15, "id"));
    rtqMethods.put("6247096756520515350", new QueriesGenerated.RTQ(16, "children"));
    rtqMethods.put("6897009001583523916", new QueriesGenerated.RTQ(17, "visit"));
    rtqMethods.put("3737166271523378550", new QueriesGenerated.RTQ(18, "parent"));
    rtqMethods.put("4798834304119524999", new QueriesGenerated.RTQ(19, "children"));
    rtqMethods.put("4798834304119566852", new QueriesGenerated.RTQ(20, "visit"));
    rtqMethods.put("2860118060025025001", new QueriesGenerated.RTQ(21, "result"));
    rtqMethods.put("2860118060024669095", new QueriesGenerated.RTQ(22, "aStringProperty"));
    rtqMethods.put("2860118060025897723", new QueriesGenerated.RTQ(23, "result"));
    rtqMethods.put("2860118060025897492", new QueriesGenerated.RTQ(24, "aChild"));
    rtqMethods.put("1229604057031378831", new QueriesGenerated.RTQ(25, "result"));
    rtqMethods.put("1229604057031381976", new QueriesGenerated.RTQ(26, "listChild"));
    rtqMethods.put("6247096756518748056", new QueriesGenerated.RTQ(27, "AT"));
    rtqMethods.put("6247096756518753322", new QueriesGenerated.RTQ(28, "COLONCOLON"));
    rtqMethods.put("4522383332296526102", new QueriesGenerated.RTQ(29, "AT"));
    rtqMethods.put("4522383332294679144", new QueriesGenerated.RTQ(30, "DummyLexer"));
    rtqMethods.put("489068675549501044", new QueriesGenerated.RTQ(31, "DummyMapper"));
    rtqMethods.put("489068675549506111", new QueriesGenerated.RTQ(32, "mapOperator"));
    rtqMethods.put("1229604057017649468", new QueriesGenerated.RTQ(33, "Object"));
  }
  @NotNull
  @Override
  public ReferenceTargetQuery getReferenceTargetQuery(@NotNull QueryKey queryKey) {
    final String id = queryKey.getTemplateNode().getNodeId().toString();
    if (!(rtqMethods.containsKey(id))) {
      return super.getReferenceTargetQuery(queryKey);
    }
    return rtqMethods.get(id);
  }
  private static class RTQ extends ReferenceTargetQuery.Base {
    private final int methodKey;
    /*package*/ RTQ(int methodKey, String templateValue) {
      super(templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull ReferenceMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.referenceMacro_GetReferent_558881339892955174(ctx);
        case 1:
          return QueriesGenerated.referenceMacro_GetReferent_558881339892896039(ctx);
        case 2:
          return QueriesGenerated.referenceMacro_GetReferent_558881339893019882(ctx);
        case 3:
          return QueriesGenerated.referenceMacro_GetReferent_558881339893021123(ctx);
        case 4:
          return QueriesGenerated.referenceMacro_GetReferent_558881339902213637(ctx);
        case 5:
          return QueriesGenerated.referenceMacro_GetReferent_6247096756522584080(ctx);
        case 6:
          return QueriesGenerated.referenceMacro_GetReferent_6247096756522340050(ctx);
        case 7:
          return QueriesGenerated.referenceMacro_GetReferent_8933086517772282807(ctx);
        case 8:
          return QueriesGenerated.referenceMacro_GetReferent_8933086517772282823(ctx);
        case 9:
          return QueriesGenerated.referenceMacro_GetReferent_8933086517774776050(ctx);
        case 10:
          return QueriesGenerated.referenceMacro_GetReferent_8933086517774776060(ctx);
        case 11:
          return QueriesGenerated.referenceMacro_GetReferent_489068675543580924(ctx);
        case 12:
          return QueriesGenerated.referenceMacro_GetReferent_1096804516885722969(ctx);
        case 13:
          return QueriesGenerated.referenceMacro_GetReferent_4798834304115678174(ctx);
        case 14:
          return QueriesGenerated.referenceMacro_GetReferent_4798834304115678633(ctx);
        case 15:
          return QueriesGenerated.referenceMacro_GetReferent_4798834304115679379(ctx);
        case 16:
          return QueriesGenerated.referenceMacro_GetReferent_6247096756520515351(ctx);
        case 17:
          return QueriesGenerated.referenceMacro_GetReferent_6897009001583523917(ctx);
        case 18:
          return QueriesGenerated.referenceMacro_GetReferent_3737166271523378551(ctx);
        case 19:
          return QueriesGenerated.referenceMacro_GetReferent_4798834304119525000(ctx);
        case 20:
          return QueriesGenerated.referenceMacro_GetReferent_4798834304119566853(ctx);
        case 21:
          return QueriesGenerated.referenceMacro_GetReferent_2860118060025025004(ctx);
        case 22:
          return QueriesGenerated.referenceMacro_GetReferent_2860118060024669098(ctx);
        case 23:
          return QueriesGenerated.referenceMacro_GetReferent_2860118060025897726(ctx);
        case 24:
          return QueriesGenerated.referenceMacro_GetReferent_2860118060025897495(ctx);
        case 25:
          return QueriesGenerated.referenceMacro_GetReferent_1229604057031378832(ctx);
        case 26:
          return QueriesGenerated.referenceMacro_GetReferent_1229604057031381977(ctx);
        case 27:
          return QueriesGenerated.referenceMacro_GetReferent_6247096756518748057(ctx);
        case 28:
          return QueriesGenerated.referenceMacro_GetReferent_6247096756518753323(ctx);
        case 29:
          return QueriesGenerated.referenceMacro_GetReferent_4522383332296526103(ctx);
        case 30:
          return QueriesGenerated.referenceMacro_GetReferent_4522383332294679145(ctx);
        case 31:
          return QueriesGenerated.referenceMacro_GetReferent_489068675549501045(ctx);
        case 32:
          return QueriesGenerated.referenceMacro_GetReferent_489068675549506112(ctx);
        case 33:
          return QueriesGenerated.referenceMacro_GetReferent_1229604057017649471(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private static SNode _quotation_createNode_x583g4_a0a0a1a05() {
    PersistenceFacade facade = PersistenceFacade.getInstance();
    SNode quotedNode_1 = null;
    quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x11d47da71ecL, "StringType"), null, null, false);
    return quotedNode_1;
  }
}
